# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soyventana.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(900, 820)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 820))
        MainWindow.setMaximumSize(QtCore.QSize(900, 820))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/soyicono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabSoy = QtWidgets.QTabWidget(self.centralwidget)
        self.tabSoy.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSoy.sizePolicy().hasHeightForWidth())
        self.tabSoy.setSizePolicy(sizePolicy)
        self.tabSoy.setMaximumSize(QtCore.QSize(16777215, 775))
        self.tabSoy.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabSoy.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabSoy.setElideMode(QtCore.Qt.ElideNone)
        self.tabSoy.setDocumentMode(False)
        self.tabSoy.setTabsClosable(False)
        self.tabSoy.setObjectName("tabSoy")
        self.tabZamba = QtWidgets.QWidget()
        self.tabZamba.setObjectName("tabZamba")
        self.groupBox_dados = QtWidgets.QGroupBox(self.tabZamba)
        self.groupBox_dados.setGeometry(QtCore.QRect(10, 10, 374, 331))
        self.groupBox_dados.setObjectName("groupBox_dados")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_dados)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.compas_01 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_01.setMinimum(2)
        self.compas_01.setMaximum(12)
        self.compas_01.setProperty("value", 7)
        self.compas_01.setObjectName("compas_01")
        self.gridLayout_2.addWidget(self.compas_01, 0, 0, 1, 1)
        self.compas_02 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_02.setMinimum(2)
        self.compas_02.setMaximum(12)
        self.compas_02.setProperty("value", 7)
        self.compas_02.setObjectName("compas_02")
        self.gridLayout_2.addWidget(self.compas_02, 0, 1, 1, 1)
        self.compas_03 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_03.setMinimum(2)
        self.compas_03.setMaximum(12)
        self.compas_03.setObjectName("compas_03")
        self.gridLayout_2.addWidget(self.compas_03, 0, 2, 1, 1)
        self.compas_04 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_04.setMinimum(2)
        self.compas_04.setMaximum(12)
        self.compas_04.setObjectName("compas_04")
        self.gridLayout_2.addWidget(self.compas_04, 0, 3, 1, 1)
        self.compas_05 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_05.setMinimum(2)
        self.compas_05.setMaximum(12)
        self.compas_05.setObjectName("compas_05")
        self.gridLayout_2.addWidget(self.compas_05, 1, 0, 1, 1)
        self.compas_06 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_06.setMinimum(2)
        self.compas_06.setMaximum(12)
        self.compas_06.setObjectName("compas_06")
        self.gridLayout_2.addWidget(self.compas_06, 1, 1, 1, 1)
        self.compas_07 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_07.setMinimum(2)
        self.compas_07.setMaximum(12)
        self.compas_07.setObjectName("compas_07")
        self.gridLayout_2.addWidget(self.compas_07, 1, 2, 1, 1)
        self.compas_08 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_08.setMinimum(2)
        self.compas_08.setMaximum(12)
        self.compas_08.setObjectName("compas_08")
        self.gridLayout_2.addWidget(self.compas_08, 1, 3, 1, 1)
        self.compas_09 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_09.setMinimum(2)
        self.compas_09.setMaximum(12)
        self.compas_09.setObjectName("compas_09")
        self.gridLayout_2.addWidget(self.compas_09, 2, 0, 1, 1)
        self.compas_10 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_10.setMinimum(2)
        self.compas_10.setMaximum(12)
        self.compas_10.setObjectName("compas_10")
        self.gridLayout_2.addWidget(self.compas_10, 2, 1, 1, 1)
        self.compas_11 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_11.setMinimum(2)
        self.compas_11.setMaximum(12)
        self.compas_11.setObjectName("compas_11")
        self.gridLayout_2.addWidget(self.compas_11, 2, 2, 1, 1)
        self.compas_12 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_12.setMinimum(2)
        self.compas_12.setMaximum(12)
        self.compas_12.setObjectName("compas_12")
        self.gridLayout_2.addWidget(self.compas_12, 2, 3, 1, 1)
        self.compas_13 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_13.setMinimum(2)
        self.compas_13.setMaximum(12)
        self.compas_13.setObjectName("compas_13")
        self.gridLayout_2.addWidget(self.compas_13, 3, 0, 1, 1)
        self.compas_14 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_14.setMinimum(2)
        self.compas_14.setMaximum(12)
        self.compas_14.setObjectName("compas_14")
        self.gridLayout_2.addWidget(self.compas_14, 3, 1, 1, 1)
        self.compas_15 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_15.setMinimum(2)
        self.compas_15.setMaximum(12)
        self.compas_15.setObjectName("compas_15")
        self.gridLayout_2.addWidget(self.compas_15, 3, 2, 1, 1)
        self.compas_16 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_16.setMinimum(2)
        self.compas_16.setMaximum(12)
        self.compas_16.setObjectName("compas_16")
        self.gridLayout_2.addWidget(self.compas_16, 3, 3, 1, 1)
        self.compas_17 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_17.setMinimum(2)
        self.compas_17.setMaximum(12)
        self.compas_17.setObjectName("compas_17")
        self.gridLayout_2.addWidget(self.compas_17, 4, 0, 1, 1)
        self.compas_18 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_18.setMinimum(2)
        self.compas_18.setMaximum(12)
        self.compas_18.setObjectName("compas_18")
        self.gridLayout_2.addWidget(self.compas_18, 4, 1, 1, 1)
        self.compas_19 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_19.setMinimum(2)
        self.compas_19.setMaximum(12)
        self.compas_19.setObjectName("compas_19")
        self.gridLayout_2.addWidget(self.compas_19, 4, 2, 1, 1)
        self.compas_20 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_20.setMinimum(2)
        self.compas_20.setMaximum(12)
        self.compas_20.setObjectName("compas_20")
        self.gridLayout_2.addWidget(self.compas_20, 4, 3, 1, 1)
        self.compas_21 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_21.setMinimum(2)
        self.compas_21.setMaximum(12)
        self.compas_21.setObjectName("compas_21")
        self.gridLayout_2.addWidget(self.compas_21, 5, 0, 1, 1)
        self.compas_22 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_22.setMinimum(2)
        self.compas_22.setMaximum(12)
        self.compas_22.setObjectName("compas_22")
        self.gridLayout_2.addWidget(self.compas_22, 5, 1, 1, 1)
        self.compas_23 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_23.setMinimum(2)
        self.compas_23.setMaximum(12)
        self.compas_23.setObjectName("compas_23")
        self.gridLayout_2.addWidget(self.compas_23, 5, 2, 1, 1)
        self.compas_24 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_24.setMinimum(2)
        self.compas_24.setMaximum(12)
        self.compas_24.setObjectName("compas_24")
        self.gridLayout_2.addWidget(self.compas_24, 5, 3, 1, 1)
        self.frame = QtWidgets.QFrame(self.groupBox_dados)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_56_910 = QtWidgets.QCheckBox(self.frame)
        self.check_56_910.setChecked(True)
        self.check_56_910.setTristate(False)
        self.check_56_910.setObjectName("check_56_910")
        self.horizontalLayout.addWidget(self.check_56_910)
        self.check_78_1112 = QtWidgets.QCheckBox(self.frame)
        self.check_78_1112.setChecked(True)
        self.check_78_1112.setTristate(False)
        self.check_78_1112.setObjectName("check_78_1112")
        self.horizontalLayout.addWidget(self.check_78_1112)
        self.botonDados = QtWidgets.QPushButton(self.frame)
        self.botonDados.setObjectName("botonDados")
        self.horizontalLayout.addWidget(self.botonDados)
        self.gridLayout_2.addWidget(self.frame, 6, 0, 1, 4)
        self.groupBox_partitura = QtWidgets.QGroupBox(self.tabZamba)
        self.groupBox_partitura.setGeometry(QtCore.QRect(390, 10, 481, 701))
        self.groupBox_partitura.setObjectName("groupBox_partitura")
        self.label = QtWidgets.QLabel(self.groupBox_partitura)
        self.label.setGeometry(QtCore.QRect(8, 35, 467, 661))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox_comunicacion = QtWidgets.QGroupBox(self.tabZamba)
        self.groupBox_comunicacion.setGeometry(QtCore.QRect(10, 480, 361, 231))
        self.groupBox_comunicacion.setObjectName("groupBox_comunicacion")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_comunicacion)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.salidaTexto = QtWidgets.QPlainTextEdit(self.groupBox_comunicacion)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.salidaTexto.setFont(font)
        self.salidaTexto.setReadOnly(True)
        self.salidaTexto.setObjectName("salidaTexto")
        self.gridLayout_5.addWidget(self.salidaTexto, 0, 0, 1, 1)
        self.groupBox_pdf = QtWidgets.QGroupBox(self.tabZamba)
        self.groupBox_pdf.setGeometry(QtCore.QRect(10, 400, 166, 71))
        self.groupBox_pdf.setObjectName("groupBox_pdf")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_pdf)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.botonPDF = QtWidgets.QPushButton(self.groupBox_pdf)
        self.botonPDF.setEnabled(False)
        self.botonPDF.setObjectName("botonPDF")
        self.gridLayout_3.addWidget(self.botonPDF, 0, 0, 1, 1)
        self.botonComponer = QtWidgets.QPushButton(self.tabZamba)
        self.botonComponer.setEnabled(False)
        self.botonComponer.setGeometry(QtCore.QRect(110, 350, 131, 35))
        self.botonComponer.setObjectName("botonComponer")
        self.groupBox_audio = QtWidgets.QGroupBox(self.tabZamba)
        self.groupBox_audio.setGeometry(QtCore.QRect(180, 400, 190, 71))
        self.groupBox_audio.setObjectName("groupBox_audio")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_audio)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.botonStop = QtWidgets.QPushButton(self.groupBox_audio)
        self.botonStop.setEnabled(False)
        self.botonStop.setObjectName("botonStop")
        self.gridLayout_4.addWidget(self.botonStop, 1, 0, 1, 1)
        self.botonPlay = QtWidgets.QPushButton(self.groupBox_audio)
        self.botonPlay.setEnabled(False)
        self.botonPlay.setObjectName("botonPlay")
        self.gridLayout_4.addWidget(self.botonPlay, 1, 1, 1, 1)
        self.tabSoy.addTab(self.tabZamba, "")
        self.gridLayout.addWidget(self.tabSoy, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 30))
        self.menubar.setObjectName("menubar")
        self.menuSoy_Legion = QtWidgets.QMenu(self.menubar)
        self.menuSoy_Legion.setObjectName("menuSoy_Legion")
        self.menuA_yuda = QtWidgets.QMenu(self.menubar)
        self.menuA_yuda.setObjectName("menuA_yuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Salir = QtWidgets.QAction(MainWindow)
        self.action_Salir.setObjectName("action_Salir")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("soyicono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcerca_de.setIcon(icon1)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.action_Ver_reglas_del_juego = QtWidgets.QAction(MainWindow)
        self.action_Ver_reglas_del_juego.setObjectName("action_Ver_reglas_del_juego")
        self.actionVer_Plantilla = QtWidgets.QAction(MainWindow)
        self.actionVer_Plantilla.setObjectName("actionVer_Plantilla")
        self.menuSoy_Legion.addAction(self.actionVer_Plantilla)
        self.menuSoy_Legion.addSeparator()
        self.menuSoy_Legion.addAction(self.action_Salir)
        self.menuA_yuda.addAction(self.action_Ver_reglas_del_juego)
        self.menuA_yuda.addSeparator()
        self.menuA_yuda.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuSoy_Legion.menuAction())
        self.menubar.addAction(self.menuA_yuda.menuAction())

        self.retranslateUi(MainWindow)
        self.tabSoy.setCurrentIndex(0)
        self.action_Salir.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabSoy, self.compas_01)
        MainWindow.setTabOrder(self.compas_01, self.compas_02)
        MainWindow.setTabOrder(self.compas_02, self.compas_03)
        MainWindow.setTabOrder(self.compas_03, self.compas_04)
        MainWindow.setTabOrder(self.compas_04, self.compas_05)
        MainWindow.setTabOrder(self.compas_05, self.compas_06)
        MainWindow.setTabOrder(self.compas_06, self.compas_07)
        MainWindow.setTabOrder(self.compas_07, self.compas_08)
        MainWindow.setTabOrder(self.compas_08, self.compas_09)
        MainWindow.setTabOrder(self.compas_09, self.compas_10)
        MainWindow.setTabOrder(self.compas_10, self.compas_11)
        MainWindow.setTabOrder(self.compas_11, self.compas_12)
        MainWindow.setTabOrder(self.compas_12, self.compas_13)
        MainWindow.setTabOrder(self.compas_13, self.compas_14)
        MainWindow.setTabOrder(self.compas_14, self.compas_15)
        MainWindow.setTabOrder(self.compas_15, self.compas_16)
        MainWindow.setTabOrder(self.compas_16, self.compas_17)
        MainWindow.setTabOrder(self.compas_17, self.compas_18)
        MainWindow.setTabOrder(self.compas_18, self.compas_19)
        MainWindow.setTabOrder(self.compas_19, self.compas_20)
        MainWindow.setTabOrder(self.compas_20, self.compas_21)
        MainWindow.setTabOrder(self.compas_21, self.compas_22)
        MainWindow.setTabOrder(self.compas_22, self.compas_23)
        MainWindow.setTabOrder(self.compas_23, self.compas_24)
        MainWindow.setTabOrder(self.compas_24, self.check_56_910)
        MainWindow.setTabOrder(self.check_56_910, self.check_78_1112)
        MainWindow.setTabOrder(self.check_78_1112, self.botonDados)
        MainWindow.setTabOrder(self.botonDados, self.botonComponer)
        MainWindow.setTabOrder(self.botonComponer, self.botonPDF)
        MainWindow.setTabOrder(self.botonPDF, self.botonStop)
        MainWindow.setTabOrder(self.botonStop, self.botonPlay)
        MainWindow.setTabOrder(self.botonPlay, self.salidaTexto)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Soy Legión"))
        self.groupBox_dados.setTitle(_translate("MainWindow", "Dados"))
        self.check_56_910.setText(_translate("MainWindow", "5-6->9-10"))
        self.check_78_1112.setText(_translate("MainWindow", "7-8->11-12"))
        self.botonDados.setText(_translate("MainWindow", "&Lanza dados"))
        self.groupBox_partitura.setTitle(_translate("MainWindow", "Partitura"))
        self.groupBox_comunicacion.setTitle(_translate("MainWindow", "Comunicación"))
        self.salidaTexto.setPlainText(_translate("MainWindow", "¿Cómo sabrá ser, no?", "Hola Mundo!"))
        self.groupBox_pdf.setTitle(_translate("MainWindow", "Partitura"))
        self.botonPDF.setText(_translate("MainWindow", "&Visor externo"))
        self.botonComponer.setText(_translate("MainWindow", "&Compone"))
        self.groupBox_audio.setTitle(_translate("MainWindow", "Audio"))
        self.botonStop.setText(_translate("MainWindow", "&Detiene"))
        self.botonPlay.setText(_translate("MainWindow", "&Toca"))
        self.tabSoy.setTabText(self.tabSoy.indexOf(self.tabZamba), _translate("MainWindow", "&Zamba para un exorcismo"))
        self.menuSoy_Legion.setTitle(_translate("MainWindow", "Soy &Legión"))
        self.menuA_yuda.setTitle(_translate("MainWindow", "A&yuda"))
        self.action_Salir.setText(_translate("MainWindow", "&Salir"))
        self.action_Salir.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAcerca_de.setText(_translate("MainWindow", "A&cerca de..."))
        self.action_Ver_reglas_del_juego.setText(_translate("MainWindow", "&Ver reglas del juego..."))
        self.actionVer_Plantilla.setText(_translate("MainWindow", "Ver &Plantilla..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

